# Syllabus {-}

### Key information {-}

* Instructor: Truong-Son Van 
* Email: [son.van+310@fulbright.edu.vn](mailto:son.van+310@fulbright.edu.vn)
* Class time: T \& Th: 9:45a - 11:15a 
* Class Location: CRES  CR 2 
* Office hours: M & W, 10a-11a (or by appointment)
* Prerequisites: Multivariable Calculus (MATH 104) and Probability (MATH 205)


## Textbooks and references  {-}
- John Rice, Mathematical Statistics & Data Analysis, 3rd Edition (main reference) 
- Cassella and Berger, Statistical Inference, 2nd Edition 
- Larry Wasserman, All of Statistics

### Course description  {-}

### Learning objectives {-}

## Assessment {-}
 
During the course, students are expected to compute their own percentage
points based on the following scheme.
The instructor is not responsible for providing the running percentage.

| **Form of assessment**      | **Weight**  |
|:---------------------------:|:-----------:|
| Weekly homeworks            | 40%         |
| Mini-project                | 15%         |
| Midterm                     | 20%         |
| Final                       | 25%         |

The following is the letter grade breakdown. It is based on
common practice in the United States.

| **Letter Grade**        | **Percentage**      |
| :---------------------: | :-----------------: |
| A                       | [93,100]          |
| A-                      | [90,93)           |
| B+                      | [87,90)             |
| B                       | [83,87)             |
| B-                      | [80, 83)            |
| C+                      | [77,80)             |
| C                       | [73,77)             |
| C-                      | [70,73)             |
| D+                      | [67,70)             |
| D                       | [60, 66)            |
| F                       | [0,60)              |

## Core content {-}

1. Probability Review (2 weeks) 
   a. Random Variables 
   b. Concentration inequality (non-asymptotic theory) 
   c. Limit Theorems (asymptotic theory) 
   d. Special distributions 
2. Sampling distribution, confidence interval (Rice, 6.3, 7.1 – 7.3) (1 week) 
3. Parameter estimation & Method of moments (Rice, 8.1 – 8.4) (1 week) 
4. Maximum likelihood estimation (Rice, 8.5) (1 week) 
5. Expection-Maximization Algorithm (Wasserman, 9.13.4) (1 week) 
6. Bayesian approach to parameter estimation (Wasserman, 11) (1 week) 
7. Unbiased estimators, Efficiency & Cramer-Rao Inequality (Casella & Berger, 7.3.2, Rice, 8.7) (1 week) 
8. Sufficiency and unbiasedness, Rao-Blackwell Theorem (Casella & Berger, 7.3.3, Rice, 8.8) (1 week) 
9. Hypothesis testings, Neyman-Pearson Lemma, Wald test, Likelihood Ratio test (Rice, 9) (2 weeks) 
10. Comparing samples (Rice, 11) (1 week) 
11. Analysis of Variance (Rice, 12) (1 week) 
12. Linear regression and least squares (Wasserman, 13.1-13.3, Casella & Berger, 11.3) (1 week)


## Project description {-}

### Project Guidelines {-}
- You may work alone or in team of two.
- You need to discuss with me a proposal for your project.
  The proposal should include your group members names & IDs, a brief description of the content of your project (as clear and explicit as possible), how you plan to present it, and a suggested grading rubric. 
- You will need to deliver a 15 minutes presentation as well as a 5-page-minimum write up in 1.5 spacing).

### Project Timeline {-}
TBD

### Possible topics {-}
TBD

## Late assignments {-}

- 15% of the possible total mark will be deducted for every 24 hrs (or part of 24 hrs) after the
deadline. Work more than 2 days late will not be accepted. 
- Except for exceptional circumstances (see [definition](https://onestop.fulbright.edu.vn/s/article/Exceptional-Circumstance)), 
  I will not extend the deadlines.

## Time expectations {-}

Some materials require time to be accustomed to. Some students are quicker than
others. However, on average, you should expect 10-15 hours per week (including class time)
on the materials in order to know the subject relatively well.

### Collaboration & Plagiarism {-}

Plagiarism is the act of submitting the intellectual property of another person as your own. It is one of the most serious of academic offenses. Acts of plagiarism include, but are not limited to:

* Copying, or allowing someone to copy, all or a part of another person's work and presenting it as your own, or not giving proper credit.

* Purchasing a paper from someone (or a website) and presenting it as your own work.

* Re-submitting your work from another course to fulfill a requirement in another course.

Further details can be found in the Code of Academic Integrity [[link](https://fulbright.edu.vn/articles/Code%20of%20Academic%20Integrity/Code%20of%20Academic%20Integrity_%20Excom%20Endorsed.pdf)].


## Learning Support {-}

In addition to your course instructors, there are other resources available to support your
academic work at Fulbright, including one-on-one consultations with learning support staff,
supplementary workshops, and both individual and group tutoring and mentoring in course
content, language learning, and academic skills. If you would like to request learning support,
please contact Fulbright Learning Support (https://learning-support.notion.site).

## Wellbeing {-}

Mental health and wellbeing are essential for the success of your academic journey. The
Fulbright Wellness Center provides various services including counseling, safer community,
and accessibility services. If you are experiencing undue personal or academic stress, are
feeling unsafe, or would like to know more about issues related to wellbeing, please contact
the Wellness Center via wellness@fulbright.edu.vn or visit the Wellness Center office on
Level 5 of the Crescent campus.

For more information, pleaes check 
https://onestop.fulbright.edu.vn/s/article/Health-and-Wellness-Introduction

\newpage

## Tentative Course Schedule {-}

TBD

